services:
- type: web
  name: leave-system
  env: python
  repo: https://github.com/bj1103/leave-system
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
  - key: GOOGLE_SERVICE_ACCOUNT_JSON
    sync: false