from linebot.v3.messaging import (
    FlexBubble,
    FlexBox,
    FlexText,
    FlexButton,
    URIAction,
)

night_timeoff_template = FlexBubble(
    body=FlexBox(
        layout="vertical",
        contents=[
            FlexText(
                text="夜假總數: ",
                weight="bold",
                size="xl",
                style="italic"
            ),
            FlexBox(
                layout="vertical",
                margin="lg",
                spacing="sm",
                contents=[
                    FlexBox(
                        layout="baseline",
                        spacing="sm",
                        contents=[
                            FlexText(
                                text="id",
                                flex=1,
                                size="md",
                                weight="bold"
                            ),
                            FlexText(
                                text="到期日",
                                flex=5,
                                size="md",
                                weight="bold"
                            )
                        ]
                    )
                ]
            )
        ]
    ),
    footer=FlexBox(
        layout="vertical",
        contents=[
            FlexButton(
                action=URIAction(
                    label="詳細資料",
                    uri="https://docs.google.com/spreadsheets/d/10o1RavT1RGKFccEdukG1HsEgD3FPOBOPMB6fQqTc_wI/edit?usp=sharing"
                )
            )
        ]
    )
)